"""set up projects

Revision ID: 7ef56e7630c0
Revises:
Create Date: 2026-06-01 21:31:40.505850

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7ef56e7630c0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "github_connections",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("account_id", sa.String(length=128), nullable=False),
        sa.Column("account_login", sa.String(length=255), nullable=False),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column("installation_id", sa.String(length=128), nullable=True),
        sa.Column("selection_mode", sa.String(length=16), nullable=False),
        sa.Column("selected_repository_ids", sa.JSON(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_github_connections_account_id"), "github_connections", ["account_id"], unique=True
    )
    op.create_index(
        op.f("ix_github_connections_account_login"),
        "github_connections",
        ["account_login"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_connections_user_id"), "github_connections", ["user_id"], unique=False
    )
    op.create_table(
        "github_repositories",
        sa.Column("connection_id", sa.String(length=36), nullable=False),
        sa.Column("repository_id", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=512), nullable=False),
        sa.Column("owner_login", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("html_url", sa.String(length=1024), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["github_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_github_repositories_connection_id"),
        "github_repositories",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_repositories_full_name"), "github_repositories", ["full_name"], unique=False
    )
    op.create_index(
        op.f("ix_github_repositories_name"), "github_repositories", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_github_repositories_owner_login"),
        "github_repositories",
        ["owner_login"],
        unique=False,
    )
    op.create_index(
        op.f("ix_github_repositories_repository_id"),
        "github_repositories",
        ["repository_id"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("repo_url", sa.String(length=1024), nullable=False),
        sa.Column("default_branch", sa.String(length=255), nullable=True),
        sa.Column("github_connection_id", sa.String(length=36), nullable=True),
        sa.Column("source_provider", sa.String(length=32), nullable=False),
        sa.Column("source_repository", sa.JSON(), nullable=True),
        sa.Column("runtime_type", sa.String(length=32), nullable=False),
        sa.Column("build_settings", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["github_connection_id"],
            ["github_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_github_connection_id"), "projects", ["github_connection_id"], unique=False
    )
    op.create_index(op.f("ix_projects_user_id"), "projects", ["user_id"], unique=False)
    op.create_table(
        "environments",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("env_vars", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_environments_project_id"), "environments", ["project_id"], unique=False
    )
    op.create_table(
        "builds",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("environment_id", sa.String(length=36), nullable=True),
        sa.Column("triggered_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("trigger_source", sa.String(length=32), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("source_snapshot", sa.JSON(), nullable=True),
        sa.Column("build_config", sa.JSON(), nullable=True),
        sa.Column("env_snapshot", sa.JSON(), nullable=True),
        sa.Column("planned_release_id", sa.String(length=36), nullable=True),
        sa.Column("builder_adapter", sa.String(length=64), nullable=True),
        sa.Column("claimed_by_service", sa.String(length=128), nullable=True),
        sa.Column("claim_expires_at", sa.DateTime(), nullable=True),
        sa.Column("queue_job_id", sa.String(length=255), nullable=True),
        sa.Column("artifact_ref", sa.String(length=1024), nullable=True),
        sa.Column("error_message", sa.String(length=4096), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_builds_builder_adapter"), "builds", ["builder_adapter"], unique=False)
    op.create_index(
        op.f("ix_builds_claim_expires_at"), "builds", ["claim_expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_builds_claimed_by_service"), "builds", ["claimed_by_service"], unique=False
    )
    op.create_index(op.f("ix_builds_correlation_id"), "builds", ["correlation_id"], unique=False)
    op.create_index(op.f("ix_builds_environment_id"), "builds", ["environment_id"], unique=False)
    op.create_index(
        op.f("ix_builds_planned_release_id"), "builds", ["planned_release_id"], unique=False
    )
    op.create_index(op.f("ix_builds_project_id"), "builds", ["project_id"], unique=False)
    op.create_index(op.f("ix_builds_queue_job_id"), "builds", ["queue_job_id"], unique=False)
    op.create_index(
        op.f("ix_builds_triggered_by_user_id"), "builds", ["triggered_by_user_id"], unique=False
    )
    op.create_table(
        "deployments",
        sa.Column("build_id", sa.String(length=36), nullable=False),
        sa.Column("environment_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("replicas", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=4096), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deployments_build_id"), "deployments", ["build_id"], unique=False)
    op.create_index(
        op.f("ix_deployments_environment_id"), "deployments", ["environment_id"], unique=False
    )
    op.create_table(
        "log_lines",
        sa.Column("build_id", sa.String(length=36), nullable=True),
        sa.Column("deployment_id", sa.String(length=36), nullable=True),
        sa.Column("stream", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_log_lines_build_id"), "log_lines", ["build_id"], unique=False)
    op.create_index(
        op.f("ix_log_lines_deployment_id"), "log_lines", ["deployment_id"], unique=False
    )
    op.create_table(
        "releases",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("environment_id", sa.String(length=36), nullable=False),
        sa.Column("build_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=True),
        sa.Column("artifact_ref", sa.String(length=1024), nullable=True),
        sa.Column("manifest_ref", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_releases_build_id"), "releases", ["build_id"], unique=False)
    op.create_index(
        op.f("ix_releases_environment_id"), "releases", ["environment_id"], unique=False
    )
    op.create_index(op.f("ix_releases_project_id"), "releases", ["project_id"], unique=False)
    op.create_table(
        "routes",
        sa.Column("hostname", sa.String(length=512), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("invalidation_version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_hostname"), "routes", ["hostname"], unique=True)
    op.create_index(op.f("ix_routes_release_id"), "routes", ["release_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("actor_service", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("build_id", sa.String(length=36), nullable=True),
        sa.Column("release_id", sa.String(length=36), nullable=True),
        sa.Column("route_id", sa.String(length=36), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_build_id"), "audit_events", ["build_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_project_id"), "audit_events", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_release_id"), "audit_events", ["release_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_route_id"), "audit_events", ["route_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_events_route_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_release_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_project_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_build_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_routes_release_id"), table_name="routes")
    op.drop_index(op.f("ix_routes_hostname"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_releases_project_id"), table_name="releases")
    op.drop_index(op.f("ix_releases_environment_id"), table_name="releases")
    op.drop_index(op.f("ix_releases_build_id"), table_name="releases")
    op.drop_table("releases")
    op.drop_index(op.f("ix_log_lines_deployment_id"), table_name="log_lines")
    op.drop_index(op.f("ix_log_lines_build_id"), table_name="log_lines")
    op.drop_table("log_lines")
    op.drop_index(op.f("ix_deployments_environment_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_build_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_builds_triggered_by_user_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_queue_job_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_project_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_planned_release_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_environment_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_correlation_id"), table_name="builds")
    op.drop_index(op.f("ix_builds_claimed_by_service"), table_name="builds")
    op.drop_index(op.f("ix_builds_claim_expires_at"), table_name="builds")
    op.drop_index(op.f("ix_builds_builder_adapter"), table_name="builds")
    op.drop_table("builds")
    op.drop_index(op.f("ix_environments_project_id"), table_name="environments")
    op.drop_table("environments")
    op.drop_index(op.f("ix_projects_user_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_github_connection_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_github_repositories_repository_id"), table_name="github_repositories")
    op.drop_index(op.f("ix_github_repositories_owner_login"), table_name="github_repositories")
    op.drop_index(op.f("ix_github_repositories_name"), table_name="github_repositories")
    op.drop_index(op.f("ix_github_repositories_full_name"), table_name="github_repositories")
    op.drop_index(op.f("ix_github_repositories_connection_id"), table_name="github_repositories")
    op.drop_table("github_repositories")
    op.drop_index(op.f("ix_github_connections_user_id"), table_name="github_connections")
    op.drop_index(op.f("ix_github_connections_account_login"), table_name="github_connections")
    op.drop_index(op.f("ix_github_connections_account_id"), table_name="github_connections")
    op.drop_table("github_connections")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
